# Copyright (C) 2025 Advanced Micro Devices, Inc. All rights reserved.
# SPDX-License-Identifier: MIT

nl_regs = {
    'mac_address': {'offset': 0x10, 'size': 8, 'type': 'rw'},
    'ip_address': {'offset': 0x18, 'size': 4, 'type': 'rw'},
    'gateway': {'offset': 0x1C, 'size': 4, 'type': 'rw'},
    'ip_mask': {'offset': 0x20, 'size': 4, 'type': 'rw'},
    'eth_in_cycles': {'offset': 0x400, 'size': 8, 'type': 'ro'},
    'eth_in_bytes': {'offset': 0x408, 'size': 8, 'type': 'ro'},
    'eth_in_packets': {'offset': 0x410, 'size': 8, 'type': 'ro'},
    'pkth_in_cycles': {'offset': 0x418, 'size': 8, 'type': 'ro'},
    'pkth_in_bytes': {'offset': 0x420, 'size': 8, 'type': 'ro'},
    'pkth_in_packets': {'offset': 0x428, 'size': 8, 'type': 'ro'},
    'arp_in_cycles': {'offset': 0x430, 'size': 8, 'type': 'ro'},
    'arp_in_bytes': {'offset': 0x438, 'size': 8, 'type': 'ro'},
    'arp_in_packets': {'offset': 0x440, 'size': 8, 'type': 'ro'},
    'arp_out_cycles': {'offset': 0x448, 'size': 8, 'type': 'ro'},
    'arp_out_bytes': {'offset': 0x450, 'size': 8, 'type': 'ro'},
    'arp_out_packets': {'offset': 0x458, 'size': 8, 'type': 'ro'},
    'icmp_in_cycles': {'offset': 0x460, 'size': 8, 'type': 'ro'},
    'icmp_in_bytes': {'offset': 0x468, 'size': 8, 'type': 'ro'},
    'icmp_in_packets': {'offset': 0x470, 'size': 8, 'type': 'ro'},
    'icmp_out_cycles': {'offset': 0x478, 'size': 8, 'type': 'ro'},
    'icmp_out_bytes': {'offset': 0x480, 'size': 8, 'type': 'ro'},
    'icmp_out_packets': {'offset': 0x488, 'size': 8, 'type': 'ro'},
    'ethhi_out_cycles': {'offset': 0x490, 'size': 8, 'type': 'ro'},
    'ethhi_out_bytes': {'offset': 0x498, 'size': 8, 'type': 'ro'},
    'ethhi_out_packets': {'offset': 0x4A0, 'size': 8, 'type': 'ro'},
    'eth_out_cycles': {'offset': 0x4A8, 'size': 8, 'type': 'ro'},
    'eth_out_bytes': {'offset': 0x4B0, 'size': 8, 'type': 'ro'},
    'eth_out_packets': {'offset': 0x4B8, 'size': 8, 'type': 'ro'},
    'udp_in_cycles': {'offset': 0x4C0, 'size': 8, 'type': 'ro'},
    'udp_in_bytes': {'offset': 0x4C8, 'size': 8, 'type': 'ro'},
    'udp_in_packets': {'offset': 0x4D0, 'size': 8, 'type': 'ro'},
    'app_out_cycles': {'offset': 0x4D8, 'size': 8, 'type': 'ro'},
    'app_out_bytes': {'offset': 0x4E0, 'size': 8, 'type': 'ro'},
    'app_out_packets': {'offset': 0x4E8, 'size': 8, 'type': 'ro'},
    'udp_out_cycles': {'offset': 0x4F0, 'size': 8, 'type': 'ro'},
    'udp_out_bytes': {'offset': 0x4F8, 'size': 8, 'type': 'ro'},
    'udp_out_packets': {'offset': 0x500, 'size': 8, 'type': 'ro'},
    'app_in_cycles': {'offset': 0x508, 'size': 8, 'type': 'ro'},
    'app_in_bytes': {'offset': 0x510, 'size': 8, 'type': 'ro'},
    'app_in_packets': {'offset': 0x518, 'size': 8, 'type': 'ro'},
    'debug_reset_counters': {'offset': 0x5F0, 'size': 4, 'type': 'rw'},
    'frequency': {'offset': 0x5F4, 'size': 4, 'type': 'ro'},
    'probes_ports': {'offset': 0x5F8, 'size': 4, 'type': 'ro'},
    'probes_mode': {'offset': 0x5FC, 'size': 4, 'type': 'ro'},
    'udp_number_sockets': {'offset': 0x810, 'size': 4, 'type': 'ro'},
    'udp_theirIP_offset': {'offset': 0x820, 'size': 4, 'type': 'rw'},
    'udp_theirPort_offset': {'offset': 0x8A0, 'size': 4, 'type': 'rw'},
    'udp_myPort_offset': {'offset': 0x920, 'size': 4, 'type': 'rw'},
    'udp_valid_offset': {'offset': 0x9A0, 'size': 4, 'type': 'rw'},
    'arp_discovery': {'offset': 0x1010, 'size': 4, 'type': 'rw'},
    'arp_valid_offset': {'offset': 0x1100, 'size': 4, 'type': 'rw'},
    'arp_ip_addr_offset': {'offset': 0x1400, 'size': 4, 'type': 'rw'},
    'arp_mac_addr_offset': {'offset': 0x1800, 'size': 4, 'type': 'rw'},
}